server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${database_url}
    username: ${database_username}
    password: ${database_password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  # Redis
  data:
    redis:
      host: localhost
      port: 6379
